export type DrinkRecipe = { title:string; category:'Cocktails'|'Martinis'; ingredients:string[]; method:string[]; glassware:string; garnish?:string };
export const drinks: DrinkRecipe[] = [
{title:'Cosmopolitan',category:'Cocktails',ingredients:['1 oz vodka','1/2 oz triple sec','1/2 oz lime juice','1/2 oz cranberry juice'],method:['Shake ingredients vigorously in a shaker with ice.','Strain into a martini glass and serve.'],glassware:'Martini glass',garnish:'Lime wedge'},
{title:'Margarita',category:'Cocktails',ingredients:['1 1/2 oz tequila','1/2 oz triple sec','1 oz lime juice','salt'],method:['Rub the rim of a cocktail glass with lime juice and dip in salt.','Shake the liquid ingredients with ice, strain into the glass and serve.'],glassware:'Cocktail glass',garnish:'Salted rim'},
{title:'Mojito',category:'Cocktails',ingredients:['3 fresh mint sprigs','2 tsp sugar','3 tbsp fresh lime juice','1 1/2 oz light rum','club soda'],method:['Crush part of the mint in a tall glass. Add sugar and lime juice and stir.','Top with ice, add rum and mix. Top with chilled club soda.'],glassware:'Tall glass',garnish:'Lemon slice and mint'},
{title:'Tom Collins',category:'Cocktails',ingredients:['2 oz gin','1 oz lemon juice','1 tsp superfine sugar','3 oz club soda'],method:['Shake gin, lemon juice and sugar with ice.','Strain into a Collins glass with ice, add club soda and stir.'],glassware:'Collins glass',garnish:'Cherry and orange slice'},
{title:'Standard Gin Martini',category:'Martinis',ingredients:['6 oz gin','5 drops dry vermouth','2 small twists lemon rind','2 olives'],method:['Chill gin in a shaker with cracked ice, then shake vigorously.','Place vermouth into chilled martini glasses and strain in the gin.'],glassware:'Martini glass',garnish:'Lemon twist and olive'},
{title:'Standard Vodka Martini',category:'Martinis',ingredients:['3 oz vodka','1 tsp vermouth','3 olives'],method:['Chill vodka in a shaker. Swirl vermouth in a frozen martini glass and pour it out.','Shake vodka vigorously and strain into the glass.'],glassware:'Martini glass',garnish:'Olives'},
{title:'Chocolate Martini',category:'Martinis',ingredients:['1 1/2 shots chocolate liqueur','1 1/2 shots crème de cacao','1/2 shot vodka','2 1/2 shots half-and-half'],method:['Mix all ingredients in a shaker with ice.','Shake and pour into a chilled cocktail glass.'],glassware:'Chilled cocktail glass'},
{title:'Apple Martini',category:'Martinis',ingredients:['1 part vodka','1 part sour apple schnapps','1 part apple juice'],method:['Pour all ingredients into a shaker.','Shake well and strain into a martini glass.'],glassware:'Martini glass'}
];